from .attn_ import MultiheadAttentionSeparateWeight
from .attn import MultiheadAttention
from .dual_attn import MultiheadDualAttention

from .attn_share_V_out_proj import MultiheadAttentionShareVOutProj
from .attn_share_attn_out_proj import MultiheadAttentionShareAttnOutProj
from .triple_attn_share_QKV_out_proj import MultiheadTripleAttention
