# # from .ks_dab_detr.ks_dab_detr_r101_70ep_smlp_qkv_triple_attn_share_outproj_ffn import (
# from .ks_dab_detr.ks_dab_detr_r101_70ep
# ks_conditional_detr.ks_conditional_detr_r101_70ep
# ks_conditional_detr_r101_70ep_smlp_qkv_triple_attn_share_outproj_ffn
# ks_conditional_detr_r50_70ep_smlp_qkv_triple_attn_share_outproj_ffn
# .ks_dn_detr.ks_dn_detr_r50_65ep
# .ks_conditional_detr.ks_conditional_detr_r101_70ep_smlp_qkv_triple_attn_share_outproj_ffn
# .ks_deformable_detr.ks_deformable_detr_r50_70ep
# ks_deformable_detr_r50_70ep_smlp_qkv_triple_attn_outproj_ffn
# .ks_deformable_detr.ks_deformable_detr_r50_70ep_smlp_qkv_triple_attn_outproj_ffn
# .ks_conditional_detr.ks_conditional_detr_r50_70ep_smlp_qkv_triple_attn_share_outproj_ffn
# ks_deformable_detr_r50_70ep_smlp_qkv_triple_attn_outproj_ffn
#ks_deformable_detr_r101_70ep_smlp_qkv_triple_attn_outproj_ffn
# from  .ks_deformable_detr.ks_deformable_detr_r50_70ep_smlp_qkv_triple_attn_outproj_ffn import (
# ks_dino_r50_4scale_70ep
#ks_dino_r50_4scale_70ep_smlp_qkv_quad_attn_outproj_ffn
# .ks_deformable_detr.ks_deformable_detr_r101_12ep

"""

ks_deformable_detr_r101_70ep.py
ks_deformable_detr_r101_70ep_smlp_qkv_quad_attn_outproj_ffn.py
ks_deformable_detr_r101_70ep_smlp_qkv_triple_attn_outproj_ffn.py
ks_deformable_detr_r50_12ep.py
ks_deformable_detr_r50_50ep.py
ks_deformable_detr_r50_70ep.py
ks_deformable_detr_r50_70ep_smlp_qkv_quad_attn_outproj_ffn.py
ks_deformable_detr_r50_70ep_smlp_qkv_triple_attn_outproj_ffn.py
.py
ks_deformable_detr_r101_12ep.py
ks_deformable_detr_r101_12ep_smlp_qkv_quad_attn_outproj_ffn.py
ks_deformable_detr_r101_12ep_smlp_qkv_triple_attn_outproj_ffn.py

ks_deformable_detr_r101_12ep_smlp_qkv_triple_attn_outproj_ffn_v0.py
ks_dino.ks_dino_r50_4scale_36ep_smlp_qkv_triple_attn_outproj_ffn
ks_dino.ks_dino_r50_4scale_12ep_smlp_qkv_triple_attn_outproj_ffn
ks_deformable_detr.ks_deformable_detr_r50_70ep_smlp_qkv_triple_attn_outproj_ffn

ks_dino_r50_4scale_12ep_smlp_qkv_triple_attn_outproj_ffn
ks_dino_r50_4scale_12ep

ks_dab_deformable_detr.
ks_dab_deformable_detr_r50_12ep.py
ks_dab_deformable_detr_r50_12ep_smlp_qkv_triple_attn_share_outproj_ffn.py
ks_dab_deformable_detr_r50_50ep.py
ks_dab_deformable_detr_r50_50ep_smlp_qkv_triple_attn_share_outproj_ffn.py
ks_dab_deformable_detr_r50_two_stage_50ep.py
ks_dab_deformable_detr.ks_dab_deformable_detr_r50_50ep_smlp_qkv_triple_attn_share_outproj_ffn
ks_dino.ks_dino_r50_4scale_12ep_small_qkv_triple_attn_v2_outproj_ffn
ks_group_detr_r50_50ep_smlp_qkv_triple_attn_share_outproj_ffn
.ks_group_detr.ks_group_detr_r50_50ep

ks_dab_detr
ks_dab_detr_swin_small_50ep.py
ks_dab_detr_swin_small_50ep_smlp_qkv_triple_attn_share_outproj_ffn.py
ks_dab_detr_swin_tiny_50ep_smlp_qkv_triple_attn_share_outproj_ffn.py
ks_dab_detr_swin_small_50ep_smlp_qkv_triple_attn_share_outproj_ffn
ks_dab_detr_r101_50ep_smlp_dual_attn_share_qk_outproj_ffn
ks_dab_detr_r101_50ep_smlp_dual_attn_share_v_outproj_ffn


ks_group_detr.ks_group_detr_r50_50ep_smlp_qkv_triple_attn_share_outproj_ffn
ks_dab_detr_r101_50ep_smlp_dual_attn_share_qk_outproj_ffn
"""
from .ks_dab_detr.ks_dab_detr_r50_50ep_smlp_qkv_triple_attn_share_outproj_ffn import (
    train,
    dataloader,
    optimizer,
    lr_multiplier,
    model,
)

# modify dataloader config
dataloader.train.num_workers = 6  # 16

# please notice that this is total batch size.
# surpose you're using 4 gpus for training and the batch size for
# each gpu is 16/4 = 4
dataloader.train.total_batch_size = 2

train.eval_period = 50
# from .models.ks_dn_detr.ks_dn_detr_w_gt_r50 import model
# from .ks_dn_detr.models.ks_dn_detr_r50_smlp_qkv_triple_attn_outproj_ffn_v0 import model
# from .ks_dab_detr.models.ks_dab_detr_r50 import model
# from .ks_dab_detr.models.ks_dab_detr_r50_smlp_qkv_triple_attn_outproj_ffn_v0 import model

# # max training iterations
# train.max_iter = 10000

#   from .ks_dn_detr.ks_dn_detr_r50_50ep import (
from .utils import get_out_dir_from_file_name
train.output_dir = get_out_dir_from_file_name(__file__, with_parent_dir=False)
dataloader.evaluator.output_dir = train.output_dir
